input_data_train_path: "data/raw/train.csv"
input_data_test_path: "data/raw/test.csv"
output_model_path: "models/model_random_forest.pkl"
output_prediction_path: "models/predictions.csv"
output_prediction_proba_path: "models/predictions_proba.csv"
metric_path: "models/metrics_random_forest.json"
downloading_params:
  train_url: "https://drive.google.com/uc?id=156Wh9zJx-3srAhqB_BbBHCMspfrcxMHG"
  test_url: "https://drive.google.com/uc?id=1VMzWpU-LgO_2Q9C-hcbQpN2tJdmXi2pz"
  train_path: train.csv
  test_path: test.csv
  output_folder: "data/raw/"
splitting_params:
  val_size: 0.2
  random_state: 17
train_params:
  model_type: "RandomForestClassifier"
  n_estimators: 150
  random_state: 17
feature_params:
  numerical_features:
    - "trestbps"
    - "chol"
    - "thalach"
  categorical_features:
    - "cp"
    - "restecg"
    - "slope"
    - "ca"
    - "thal"
  simple_categorical_features:
    - "sex"
    - "fbs"
    - "exang"
  transformer_features_log:
    - "age"
  transformer_features_square:
    - "age"
    - "chol"
  target_col: "condition"
